[project]
name = "algorithms-project-69"
version = "0.1.0"
description = "Search Engine for hexlet course"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
    "ruff>=0.8.3",
]